services:
  api:
    build:
      context: .
      dockerfile: DockerFile.api
    image: miniserve-api:latest
    ports:
      - "8000:8000"

  inference:
    build:
      context: .
      dockerfile: DockerFile.worker
    image: miniserve-worker:latest
    command: ["--benchmark", "20"]
    profiles:
      - day1
